FROM oven/bun:1-alpine

WORKDIR /app

COPY package.json ./
RUN bun install

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]
